### ISSUE TITLE
Could you tell me how to use this package?

### ISSUE THREAD

**Issue by Sunny-NEU** [captnjohnny1618/CTBB_PRM#1]
Hi, I'm looking for PRM to doing CT image registration. i'm not sure if it is and how to use it because i found nothing in README .

**Comment by captnjohnny1618** [comment]
Hi Sunny!

Sorry about the delay.  Been busy at my new job. Unfortunately I was never able to get PRM running in a robust, satisfactory way.  This package was just a placeholder for some of the experiments that I was previously running.  

If you look at the "Windows Sync" branch, there is much more code than in master.  If I recall correctly, the file at https://github.com/captnjohnny1618/CTBB_PRM/blob/windows_sync/CTBB_PRM/regis_affine_bspline.py had the most promise of getting PRM to run, however it does also rely on a proprietary segmentation routine to obtain the lung segmentations (which you would would need to modify to run your own automated segmentation).

Please feel free to use any of the code you find in the repository!

Best,
John
